// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using ORCA.Api.Data;

#nullable disable

namespace ORCA.Api.Migrations
{
    [DbContext(typeof(OrcaDbContext))]
    [Migration("20260331185507_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ORCA.Api.Domain.Entities.CompatibilityOverride", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("BaseSku")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("base_sku");

                    b.Property<string>("CompatibleSku")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("compatible_sku");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("OverrideType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("override_type");

                    b.Property<string>("Reason")
                        .HasColumnType("text")
                        .HasColumnName("reason");

                    b.HasKey("Id");

                    b.HasIndex("BaseSku");

                    b.HasIndex("CompatibleSku");

                    b.HasIndex("BaseSku", "CompatibleSku", "OverrideType")
                        .IsUnique()
                        .HasDatabaseName("uq_compatibility_override");

                    b.ToTable("compatibility_overrides", (string)null);
                });

            modelBuilder.Entity("ORCA.Api.Domain.Entities.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Attributes")
                        .HasColumnType("jsonb")
                        .HasColumnName("attributes");

                    b.Property<string>("Brand")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("brand");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("category");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Family")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("family");

                    b.Property<decimal?>("Height")
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("height");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("text")
                        .HasColumnName("image_url");

                    b.Property<decimal?>("Length")
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("length");

                    b.Property<string>("NominalDimensions")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("nominal_dimensions");

                    b.Property<string>("ProductName")
                        .HasColumnType("text")
                        .HasColumnName("product_name");

                    b.Property<string>("ProductPageUrl")
                        .HasColumnType("text")
                        .HasColumnName("product_page_url");

                    b.Property<int?>("Ranking")
                        .HasColumnType("integer")
                        .HasColumnName("ranking");

                    b.Property<string>("Series")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("series");

                    b.Property<string>("Sku")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("sku");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.Property<decimal?>("Width")
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("width");

                    b.HasKey("Id");

                    b.HasIndex("Brand");

                    b.HasIndex("Category");

                    b.HasIndex("Family");

                    b.HasIndex("Series");

                    b.HasIndex("Sku")
                        .IsUnique();

                    b.ToTable("products", (string)null);
                });

            modelBuilder.Entity("ORCA.Api.Domain.Entities.ProductCompatibility", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("BaseProductId")
                        .HasColumnType("integer")
                        .HasColumnName("base_product_id");

                    b.Property<int>("CompatibleProductId")
                        .HasColumnType("integer")
                        .HasColumnName("compatible_product_id");

                    b.Property<DateTime>("ComputedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("computed_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("IncompatibilityReason")
                        .HasColumnType("text")
                        .HasColumnName("incompatibility_reason");

                    b.Property<string>("MatchReason")
                        .HasColumnType("text")
                        .HasColumnName("match_reason");

                    b.HasKey("Id");

                    b.HasIndex("BaseProductId")
                        .HasDatabaseName("idx_compatibility_base");

                    b.HasIndex("CompatibleProductId")
                        .HasDatabaseName("idx_compatibility_compatible");

                    b.HasIndex("BaseProductId", "CompatibleProductId")
                        .IsUnique()
                        .HasDatabaseName("uq_product_compatibility");

                    b.ToTable("product_compatibility", (string)null);
                });

            modelBuilder.Entity("ORCA.Api.Domain.Entities.SyncStatus", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CompatibilitiesUpdated")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("compatibilities_updated");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_at");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("text")
                        .HasColumnName("error_message");

                    b.Property<int>("ProductsAdded")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("products_added");

                    b.Property<int>("ProductsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("products_deleted");

                    b.Property<int>("ProductsUpdated")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("products_updated");

                    b.Property<DateTime>("StartedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<string>("SyncMetadata")
                        .HasColumnType("jsonb")
                        .HasColumnName("sync_metadata");

                    b.Property<string>("SyncType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("sync_type");

                    b.HasKey("Id");

                    b.HasIndex("StartedAt")
                        .HasDatabaseName("idx_sync_status_started");

                    b.HasIndex("SyncType")
                        .HasDatabaseName("idx_sync_status_type");

                    b.ToTable("sync_status", (string)null);
                });

            modelBuilder.Entity("ORCA.Api.Domain.Entities.ProductCompatibility", b =>
                {
                    b.HasOne("ORCA.Api.Domain.Entities.Product", "BaseProduct")
                        .WithMany("CompatibilitiesFrom")
                        .HasForeignKey("BaseProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ORCA.Api.Domain.Entities.Product", "CompatibleProduct")
                        .WithMany("CompatibilitiesTo")
                        .HasForeignKey("CompatibleProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BaseProduct");

                    b.Navigation("CompatibleProduct");
                });

            modelBuilder.Entity("ORCA.Api.Domain.Entities.Product", b =>
                {
                    b.Navigation("CompatibilitiesFrom");

                    b.Navigation("CompatibilitiesTo");
                });
#pragma warning restore 612, 618
        }
    }
}
